### ISSUE TITLE
boolear index error

### ISSUE THREAD

**Issue by cy-yong** [cwmok/LapIRN#14] opened 2022-06-29 07:42 UTC
![image](https://user-images.githubusercontent.com/79499756/176379518-4ec1d37b-327c-45c8-abef-81a65ecfd5d0.png)
I'm sorry to bother you. When I used my data set to reproduce your code, there was such a mistake in trainingLvl3, is it related to the size of the input image? Could you tell me how to solve it

**Comment by cwmok** [comment] 2022-06-29 10:02
Hi @cy-yong,

I think so. It seems there is a size discrepancy in the "X_Y_label" and "Y_label". Make sure the size of the "X_Y_label" and "Y_label" are the same.

**Comment by cy-yong** [comment] 2022-06-30 01:57
> Hi @cy-yong,
> 
> I think so. It seems there is a size discrepancy in the "X_Y_label" and "Y_label". Make sure the size of the "X_Y_label" and "Y_label" are the same.

I find that the size of your Lables image is 256*256*256, but mine is 197*189*233. How should I modify the code or do I need to preprocess it

**Comment by cwmok** [comment] 2022-06-30 02:53
Both options work in this case. 
I prefer to use             
X = F.interpolate(X, size=imgshape, mode='trilinear')
Y = F.interpolate(Y, size=imgshape, mode='trilinear')
to resize the image + label.

Note: for labels, you should use mode='nearest'.

**Comment by cy-yong** [comment] 2022-06-30 03:13
> Both options work in this case. I prefer to use X = F.interpolate(X, size=imgshape, mode='trilinear') Y = F.interpolate(Y, size=imgshape, mode='trilinear') to resize the image + label.
> 
> Note: for labels, you should use mode='nearest'. Our label size is in (160, 192, 224), but not (256, 256, 256).

Yes, I noticed that your label is (160,192,224), but that seems to be the aligned image, I wonder if you preprocessed it, The same error occurred when I used mode='nearest' and I didn't know if I should change the code like this。
![image](https://user-images.githubusercontent.com/79499756/176585004-6fa95e0e-0f61-49f4-aaab-9d963ec60db3.png)

**Comment by cwmok** [comment] 2022-06-30 04:04
You should have a fixed image size for all the labels, e.g., ori_imgshape = (160, 192, 224).

Double-check the size of X_label and Y_label. If they are different in size, you should pre-process them to make them the same size.

Alternatively, you can evaluate the model performance with resized labels. 
1. Remove `F_X_Y = F.interpolate(F_X_Y, size=ori_imgshape, mode='trilinear', align_corners=True)`
2.  Add X_label = F.interpolate(X, size=imgshape, mode='nearest') and Y_label = F.interpolate(Y, size=imgshape, mode='nearest')

**Comment by cy-yong** [comment] 2022-06-30 09:12
> 您应该为所有标签设置一个固定的图像大小，例如 ori_imgshape = (160, 192, 224)。
> 
> 仔细检查 X_label 和 Y_label 的大小。如果它们的大小不同，您应该对它们进行预处理以使其大小相同。
> 
> 或者，您可以使用调整大小的标签来评估模型性能。
> 
> 1. 消除`F_X_Y = F.interpolate(F_X_Y, size=ori_imgshape, mode='trilinear', align_corners=True)`
> 2. 添加`X_label = F.interpolate(X, size=imgshape, mode='nearest')`和`Y_label = F.interpolate(Y, size=imgshape, mode='nearest')`
> 
> `print(X.shape)`提示：您可以使用或打印图像尺寸（X 和 Y）和标签尺寸（X_label 和 Y_label）`print(X_label.shape)`。它将帮助您在服务器端调试代码。

![image](https://user-images.githubusercontent.com/79499756/176639273-e99477df-66d0-429f-b27d-a138ead8cd22.png)
weather It is  a matter of size between the label and the original image

**Comment by cwmok** [comment] 2022-06-30 13:10
Hi @cy-yong,

The problem is now related to the size discrepancy in `F_X_Y` and `grid_unit`.

You need to use the `grid` which is the same size of F_X_Y. (See lines 329 and 330 in [here](https://github.com/cwmok/LapIRN/blob/3290c8dd4403c2816efbb2c7d8a72439b0593c4e/Code/Train_LapIRN_diff_resize.py#L329-L330))
`X_Y_label = transform_nearest(X_label, F_X_Y.permute(0, 2, 3, 4, 1), grid).cpu().numpy()[0, 0, :, :, :]`

**Comment by cy-yong** [comment] 2022-07-01 01:40
> Hi @cy-yong,
> 
> The problem is now related to the size discrepancy in `F_X_Y` and `grid_unit`.
> 
> You need to use the `grid` which is the same size of F_X_Y. (See lines 329 and 330 in [here](https://github.com/cwmok/LapIRN/blob/3290c8dd4403c2816efbb2c7d8a72439b0593c4e/Code/Train_LapIRN_diff_resize.py#L329-L330)) `X_Y_label = transform_nearest(X_label, F_X_Y.permute(0, 2, 3, 4, 1), grid).cpu().numpy()[0, 0, :, :, :]`
Sorry to bother you again, but I have a new problem, why num_count is 0, is there a data loading error
![image](https://user-images.githubusercontent.com/79499756/176805660-bff95df0-0dd4-45fb-8939-3663a055520f.png)

**Comment by cwmok** [comment] 2022-07-01 02:57
Hi @cy-yong,

It seems that some of your Y_label have zero class. You may add
`if num_count == 0: return 1` before line 83.

This will bypass the dice result when Y_label is empty/blank and return 1.

**Comment by cy-yong** [comment] 2022-07-01 07:48
> Hi @cy-yong,
> 
> It seems that some of your Y_label have zero class. You may add `if num_count == 0: return 1` before line 83.
> 
> This will bypass the dice result when Y_label is empty/blank and return 1.

![image](https://user-images.githubusercontent.com/79499756/176849326-b2e98401-3cb6-45c5-90ac-3fc130500634.png)
If there is something wrong with my code modification, I try to print num_count and I find that it is always equal to 0.

**Comment by cwmok** [comment] 2022-07-01 10:36
I don't see any problem in your screenshot. Maybe you should attach 1-2 samples image and its label for my reference?

**Comment by cy-yong** [comment] 2022-07-04 01:46
> 我在您的屏幕截图中没有看到任何问题。也许您应该附上 1-2 个示例图像及其标签（以及修改后的代码）供我参考？

I have sent an email to your mailbox. I hope you can help me solve some problems after reading it. Thank you!

**Comment by cy-yong** [comment] 2022-07-04 06:41
> I don't see any problem in your screenshot. Maybe you should attach 1-2 sample images and its label (and the modified code) for my reference?

![image](https://user-images.githubusercontent.com/79499756/177096428-a893352d-50d0-450f-aa3d-8088ed627df1.png)
Hello, senior, is this your mailbox?

**Comment by cwmok** [comment] 2022-07-04 08:13
Hi @cy-yong,

I have received your sample image. Your image label is the segmentation of brain lesions, which is not the anatomical structures we used in the provided example. In that case, you may rewrite your validation code or simply remove the validation part from the training code.

Since the training is unsupervised, it will work even if you didn't provide any label. In particular, you may remove these [lines](https://github.com/cwmok/LapIRN/blob/3290c8dd4403c2816efbb2c7d8a72439b0593c4e/Code/Train_LapIRN_diff_resize.py#L400-L435) and start your training.

**Comment by cy-yong** [comment] 2022-07-04 08:29
> Hi @cy-yong,
> 
> I have received your sample image. Your image label is the segmentation of brain lesions, which is not the anatomical structures we used in the provided example. In that case, you may rewrite your validation code or simply remove the validation part from the training code.
> 
> Since the training is unsupervised, it will work even if you didn't provide any label. In particular, you may remove these [lines](https://github.com/cwmok/LapIRN/blob/3290c8dd4403c2816efbb2c7d8a72439b0593c4e/Code/Train_LapIRN_diff_resize.py#L400-L435) and start your training.
Thank you for your reply. I seem to understand what you mean. I can delete those lines you told me and get the model through unsupervised training based on my data, right？

**Comment by cy-yong** [comment] 2022-07-04 08:39
> 是，对的。由于您正在使用大脑图像进行训练，因此默认超参数（lambda、学习率等）应该适用于您的情况。

There is another problem that I need to consult my predecessors. After load these data and completing unsupervised training, I should get a *. PTH model file, but my ultimate goal is to get warped images of all sample images, and I found that warped images passed one-to-one registration in the test stage. Do I need one-to-one registrate those images by use trained models.

**Comment by cwmok** [comment] 2022-07-04 08:50
You can either 1) write a bash script to pass these images as arguments one-by-one to the predefined test script in [Test_LapIRN_diff_resize.py ](https://github.com/cwmok/LapIRN/blob/master/Code/Test_LapIRN_diff_resize.py).

or 2) follow the training script in [Train_LapIRN_diff_resize.py](https://github.com/cwmok/LapIRN/blob/3290c8dd4403c2816efbb2c7d8a72439b0593c4e/Code/Train_LapIRN_diff_resize.py#L344-L357) to create a data generator and for-loop to loop through all your images.

**Comment by cy-yong** [comment] 2022-07-04 09:03
> 您可以 1) 编写一个 bash 脚本，将这些图像作为参数一个接一个地传递给[Test_LapIRN_diff_resize.py](https://github.com/cwmok/LapIRN/blob/master/Code/Test_LapIRN_diff_resize.py)中的预定义测试脚本。
> 
> 或 2) 按照[Train_LapIRN_diff_resize.py](https://github.com/cwmok/LapIRN/blob/3290c8dd4403c2816efbb2c7d8a72439b0593c4e/Code/Train_LapIRN_diff_resize.py#L344-L357)中的训练脚本创建数据生成器和 for 循环以遍历所有图像。

Thank you. I will try. After I finish train and generate a model, I can register all images with a fixed image, right?

**Comment by cy-yong** [comment] 2022-07-04 09:03
> 您可以 1) 编写一个 bash 脚本，将这些图像作为参数一个接一个地传递给[Test_LapIRN_diff_resize.py](https://github.com/cwmok/LapIRN/blob/master/Code/Test_LapIRN_diff_resize.py)中的预定义测试脚本。
> 
> 或 2) 按照[Train_LapIRN_diff_resize.py](https://github.com/cwmok/LapIRN/blob/3290c8dd4403c2816efbb2c7d8a72439b0593c4e/Code/Train_LapIRN_diff_resize.py#L344-L357)中的训练脚本创建数据生成器和 for 循环以遍历所有图像。

Thank you. I will try. After I finish train and generate a model, I can register all images with a fixed image, right?

**Comment by cy-yong** [comment] 2022-07-04 09:09
> Yes.

ok,If you encounter new problems, I hope you can also consult seniors

**Comment by cwmok** [comment] 2022-07-04 09:12
Stay connected. Let me know if you have further questions. Happy coding!

**Comment by cy-yong** [comment] 2022-07-06 02:03
> Stay connected. Let me know if you have further questions. Happy coding!

![image](https://user-images.githubusercontent.com/79499756/177451498-7b6acf1c-6eba-4010-afc8-5d37a41ef28e.png)
![Uploading image.png…]()
hello, senior, When I randomly selected an image as a move image and another image as a fixed image, I encountered such a size problem.

**Comment by cwmok** [comment] 2022-07-06 02:12
This is not related to the image size.
You can fix it by changing the default "[start_channel](https://github.com/cwmok/LapIRN/blob/3290c8dd4403c2816efbb2c7d8a72439b0593c4e/Code/Test_LapIRN_diff_resize.py#L20)" from 7 to 6.

**Comment by cy-yong** [comment] 2022-07-06 02:27
> This is not related to the image size. You can fix it by changing the default "[start_channel](https://github.com/cwmok/LapIRN/blob/3290c8dd4403c2816efbb2c7d8a72439b0593c4e/Code/Test_LapIRN_diff_resize.py#L20)" from 7 to 6.

![image](https://user-images.githubusercontent.com/79499756/177454461-a8e1b335-5b19-40a4-a3eb-ac19dc04eaca.png)
![image](https://user-images.githubusercontent.com/79499756/177454539-d2b2e109-09f3-4ba7-8990-9e7a0664436d.png)
The first error occurs when I use mode='trilinear' and the second error occurs when I use mode='nearest'.

**Comment by cwmok** [comment] 2022-07-06 11:41
The first error is caused by the size mismatch of the grid and flow. I have updated "Test_LapIRN_diff_resize.py" to solve this issue. (1. [Create a full-size grid.](https://github.com/cwmok/LapIRN/blob/549a40329d4e8304e35c6f0113c46ad8d7a6da32/Code/Test_LapIRN_diff_resize.py#L58-L59) 2. [Apply the full-size grid to an image](https://github.com/cwmok/LapIRN/blob/549a40329d4e8304e35c6f0113c46ad8d7a6da32/Code/Test_LapIRN_diff_resize.py#L77).)

The second error is caused by the extra argument "align_corners". When mode='nearest', you should remove the "align_corners" argument.

**Comment by cy-yong** [comment] 2022-07-07 02:12
> 第一个错误是由网格和流的大小不匹配引起的。我已经更新了“Test_LapIRN_diff_resize.py”来解决这个问题。（1.[创建全尺寸网格](https://github.com/cwmok/LapIRN/blob/549a40329d4e8304e35c6f0113c46ad8d7a6da32/Code/Test_LapIRN_diff_resize.py#L58-L59)。2.[将全尺寸网格应用于图像](https://github.com/cwmok/LapIRN/blob/549a40329d4e8304e35c6f0113c46ad8d7a6da32/Code/Test_LapIRN_diff_resize.py#L77)。）
> 
> 第二个错误是由额外的参数“align_corners”引起的。当 mode='nearest' 时，您应该删除“align_corners”参数。

![image](https://user-images.githubusercontent.com/79499756/177674935-4b03aa41-a4c7-48c2-b18f-83220e041059.png)
![image](https://user-images.githubusercontent.com/79499756/177674969-ac8b5b00-f457-4c7c-8339-5ef811548cee.png)
When I completed the training with the data set, my result in the test phase was as bad as the second figure. My original image was 197*189*233, and the registration image was 160*192*144. Is this the result caused by the image size.

**Comment by cwmok** [comment] 2022-07-07 02:19
The result is abnormal. Could you send the fixed image, moving image, trained model (.pth) and the modified script to my email?

**Comment by cwmok** [comment] 2022-07-07 02:44
Follow-up: Adding [these lines](https://github.com/cwmok/LapIRN/blob/583b32d0b469108de2b1a7369b6f66803c45d74b/Code/Test_LapIRN_diff_resize.py#L67-L71) to the test script may solve your issue. If the problem persists, feel free to send the fixed image, moving image, trained model (.pth) and the modified script to my email.

**Comment by cy-yong** [comment] 2022-07-08 01:58
> Hi @cy-yong,
> 
> This issue is caused by the background intensity of your images. You should preprocess the data such that the background intensity of each image is equal to zero.
> 
> When the background intensity is not equal to zero, the "background" will be regarded as the region of interest of the registration and the network will learn to match the backgrounds of fixed and moving images. (Because matching the background will yield the highest similarity score in this case.)
> 
> Alternatively, you can manually define your region of interest by creating a mask for each image, see masking [here](https://simpleelastix.readthedocs.io/Introduction.html#masks) for more details.
> 
> I highly suggest you follow our standard preprocessing pipeline using [FreeSurfer](https://surfer.nmr.mgh.harvard.edu/) as described in our paper. This will factor out most of the possible linear misalignment and significantly improve the registration accuracy.

I should use Free Surfer for standardized pre-processing, Skull stripping, spatial normalization and subcortical

Structures segmentation?

**Comment by cwmok** [comment] 2022-07-08 02:00
Yes, this is also the pre-processing pipeline of VoxelMorph.

**Comment by cy-yong** [comment] 2022-07-08 03:11
> Yes, this is also the pre-processing pipeline of VoxelMorph.

I want to ask that "make the background intensity of each image is equal to zero" is which one of the above steps?

**Comment by cwmok** [comment] 2022-07-08 03:22
Skull stripping/Brain extraction.

**Comment by cy-yong** [comment] 2022-07-08 03:26
> 颅骨剥离/大脑提取。



> 颅骨/抽取。

Thank you, I will continue to complete the preprocessing later, but it is still in the freesurfer installation stage

**Comment by cwmok** [comment] 2022-07-12 06:00
Hi @cy-yong,

This [page ](https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/blob/main/PreprocessingMRI.md)summarizes the required steps for using Freesurfer to preprocess brain MR images.

**Comment by cy-yong** [comment] 2022-07-12 06:36
> Hi @cy-yong,
> 
> This [page ](https://github.com/junyuchen245/TransMorph_Transformer_for_Medical_Image_Registration/blob/main/PreprocessingMRI.md)summarizes the required steps for using Freesurfer to preprocess brain MR images.

Thank you very much, I found that only some of these steps were mentioned in the paper, do I only need to complete the mentioned steps？

**Comment by cwmok** [comment] 2022-07-12 06:45
No, you don't have to. If you just want to normalize your image, recon-all -autorecon1 will be sufficient. If you also want segmentations, do -autorecon2 as well.

**Comment by cy-yong** [comment] 2022-07-13 02:23
> No, you don't have to. If you just want to normalize your image, recon-all -autorecon1 will be sufficient. If you also want segmentations, do -autorecon2 as well.

![image](https://user-images.githubusercontent.com/79499756/178637262-92beb354-b58b-485c-98ca-ca0e1c777bc6.png)
This error occurred when I was training with data processed by Freesurfer.

**Comment by cwmok** [comment] 2022-07-13 02:32
Setting `imgshape` to a smaller number will help or checking whether you are running other training at the same time.
This error is related to not having enough GPU memory.

**Comment by cy-yong** [comment] 2022-07-13 02:35
> Setting `imgshape` to a smaller number will help or checking whether you are running other training at the same time. This error is related to not having enough GPU memory.

I have sent my original image and pre-processed image to your mailbox. May I ask whether my processing process is correct？

**Comment by cwmok** [comment] 2022-07-13 02:38
I did send you a reply. But it seems that your mailbox is broken.

![image](https://user-images.githubusercontent.com/63316551/178639038-154817fe-7a90-4459-aac5-de1f7b37041f.png)

**Comment by cy-yong** [comment] 2022-07-13 02:43
> Setting `imgshape` to a smaller number will help or checking whether you are running other training at the same time. This error is related to not having enough GPU memory.
I did recon-all-Autorecon1 and converted the obtained.mgz file to.nii.gz file as required。

**Comment by cy-yong** [comment] 2022-07-13 02:43
> I did send you a reply. But it seems that your mailbox is broken.
> 
> ![image](https://user-images.githubusercontent.com/63316551/178639038-154817fe-7a90-4459-aac5-de1f7b37041f.png)

I did recon-all-Autorecon1 and converted the obtained.mgz file to.nii.gz file as required.

**Comment by cwmok** [comment] 2022-07-13 02:47
Check out the norm.mgz file instead.

**Comment by cwmok** [comment] 2022-07-13 02:48
See https://surfer.nmr.mgh.harvard.edu/fswiki/mri_normalize as well.

**Comment by cwmok** [comment] 2022-07-13 02:55
For your reference, [norm_and_brainmask_nii.zip](https://github.com/cwmok/LapIRN/files/9098564/norm_and_brainmask_nii.zip)

**Comment by cwmok** [comment] 2022-07-13 02:56
Image with skull:
[orig.nii.zip](https://github.com/cwmok/LapIRN/files/9098575/orig.nii.zip)

**Comment by cy-yong** [comment] 2022-07-13 03:10
> 另[请参阅 https://surfer.nmr.mgh.harvard.edu/fswiki/mri_normalize](https://surfer.nmr.mgh.harvard.edu/fswiki/mri_normalize)。

Do I need to normalize based on this?

**Comment by cwmok** [comment] 2022-07-13 03:14
Not necessary. But you should check the correctness norm.mgz and brainmask.mgz files.

**Comment by cy-yong** [comment] 2022-07-14 02:09
[preprocess.zip](https://github.com/cwmok/LapIRN/files/9107766/preprocess.zip)
When I completed recon-all according to the link you gave me, I found that the norm. MGZ and brainmask. MGZ files I got were wrong. I don't know which step was wrong, I hope you can help me, thank you very much！

**Comment by cwmok** [comment] 2022-07-14 02:55
Hi @cy-yong,

This is not a trivial problem. Maybe you should try simpler solutions?
1. Add `img_A = np.clip(img_A, a_min=10., a_max=np.max(img_A))` and `img_B = np.clip(img_B, a_min=10., a_max=np.max(img_B))` under these [lines](https://github.com/cwmok/LapIRN/blob/583b32d0b469108de2b1a7369b6f66803c45d74b/Code/Functions.py#L127-L128) of code.

2. Add `fixed_img = np.clip(fixed_img, a_min=10., a_max=np.max(fixed_img))` and `moving_img = np.clip(moving_img, a_min=10., a_max=np.max(moving_img))` under these [lines](https://github.com/cwmok/LapIRN/blob/583b32d0b469108de2b1a7369b6f66803c45d74b/Code/Test_LapIRN_diff_resize.py#L64-L65) of code.

3. Note that `a_min` is not necessarily equal to 10. It should be set to the maximum background intensity of your datasets.

The ultimate goal is to make sure the background of your images has zero intensity.

Let me know whether this trick works for you.

**Comment by cy-yong** [comment] 2022-07-18 03:03
[warpped_moving-68-69.nii.gz](https://github.com/cwmok/LapIRN/files/9129210/warpped_moving-68-69.nii.gz)
[warpped_moving-68-69-8.0.nii.gz](https://github.com/cwmok/LapIRN/files/9129212/warpped_moving-68-69-8.0.nii.gz)

Here's what I did with 10. And 8. I don't know if I should make a_min smaller or bigger.

**Comment by cwmok** [comment] 2022-07-18 07:09
Dear cy-yong,

I have created a tailor-made version for your dataset. You may download it via here: [For_cyyong.zip](https://github.com/cwmok/LapIRN/files/9130069/For_cyyong.zip)

The training is not stable with our NCC similarity function (even with the clip method), probably because of the noise presented in the background has high intensity value as well.

As such, we changed it to MSE function. In our tailor-made version, we train our network without progressive training strategy and train it with image resolution `imgshape = (128, 128, 128)`. I trained it with disp/diff version for 1000 iterations, the results are stable.

Feel free to finetune the `dest="smooth", default=0.1,` to control the smoothness of the solutions. In order to obtain better results, you are recommended to train the network with at least 30000 iterations.

I think the problem is completely solved by now. Feel free to let me know if you need any further help. 

Remember to close this issue if you think the problem is solved. Leave a star to this repository if you think it is useful.

**Comment by cy-yong** [comment] 2022-07-18 08:15
Thank you very much for your efforts, I will leave a star to this repository, I successfully reproduce your code, I find that the code does not train LVL1 and LVL2, I only need to train LVL3 with my data, right?

**Comment by cwmok** [comment] 2022-07-18 08:19
Yes. LV1 and LV2 are optional in your case.

**Comment by cy-yong** [comment] 2022-07-18 08:22
> 是的。在您的情况下，LV1 和 LV2 是可选的。

Are LV1 and LV2 helpful to LVL3?

**Comment by cwmok** [comment] 2022-07-18 08:29
Not sure about it with your dataset. You can try it out and let me know. In the OASIS dataset, it helps to further improve the performance.

**Comment by cy-yong** [comment] 2022-07-18 08:45
> Not sure about it with your dataset. You can try it out and let me know. In the OASIS dataset, it helps to further improve the performance.

I will try and inform you. Thank you again for your efforts.

**Comment by cwmok** [comment] 2022-07-18 08:54
>> Can our code run on multiple graphics cards? When I changed the code to Figure 1, only GUP0 worked

I don't think it works. Since we only train it with batch size = 1, multi-GPU will not accelerate the training in that case. You may need to do some refinement in order to train it with multi-GPU.

**Comment by cy-yong** [comment] 2022-07-18 08:57
> > > 我们的代码可以在多个显卡上运行吗？当我将代码更改为图 1 时，只有 GUP0 工作正常
> 
> 我认为它不起作用。由于我们仅使用批大小 = 1 对其进行训练，因此在这种情况下，多 GPU 不会加速训练。您可能需要进行一些优化，以便使用多 GPU 对其进行训练。
Ok, thank you. I'll try to optimize it

**Closed** 2022-07-20 01:57 UTC

**Comment by cwmok** [comment] 2022-07-29 09:29
Hi @cy-yong,

I remember you tried to use the Freesurfer for skull stripping in your dataset but failed. Recently, I came across a method called "SynthStrip" which may work for your dataset.

I left the link to SynthStrip here: https://surfer.nmr.mgh.harvard.edu/docs/synthstrip/

Feel free to let me know the result.

**Comment by cy-yong** [comment] 2022-10-11 08:09
Dear cwmok
&nbsp;&nbsp;I'm really sorry to tell you that I haven't been able to reproduce the link you gave me. I don't know which link went wrong and Docker can't be used normally！
&nbsp;&nbsp;I hope you can answer it, thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cwmok/LapIRN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月29日(星期五) 下午5:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cwmok/LapIRN] boolear index error (Issue #14)





 
Hi @cy-yong,
 
I remember you tried to use the Freesurfer for skull stripping in your dataset but failed. Recently, I came across a method called "SynthStrip" which may work for your dataset.
 
I left the link to SynthStrip here: https://surfer.nmr.mgh.harvard.edu/docs/synthstrip/
 
Feel free to let me know the result.
